{% set name = "zope.deferredimport" %}
{% set version = "5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zope_deferredimport-{{ version }}.tar.gz
  sha256: 9a4781b4382cbdb53f661a2b45a0acca8c22b5af835a49f99b548ac9c16d06ef

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - zope.proxy

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/zopefoundation/zope.deferredimport
  license: ZPL 2.1
  license_family: OTHER
  license_file: LICENSE.txt
  summary: 'defers import to when objects are actually used'
  description: |
    Often, especially for package modules, you want to import names for
    convenience, but not actually perform the imports until necessary.
    The zope.deferredimport package provided facilities for defining
    names in modules that will be imported from somewhere else when
    used. You can also cause deprecation warnings to be issued when a
    variable is used.
  doc_url: https://zopedeferredimport.readthedocs.io/
  dev_url: https://github.com/zopefoundation/zope.deferredimport

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - daf
